spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_management?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    password: 1234
    username: root
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update